import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import '../globals.css';
import AdminAuthProvider from '@/stores/AdminAuthProvider';

const geistSans = Geist({
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} ${geistMono.className}`}>
        <div className="flex flex-col min-h-screen">
          <AdminAuthProvider>
            <div className="flex flex-col flex-1">{children}</div>
          </AdminAuthProvider>
        </div>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
